### ISSUE TITLE
Visualizing raw tif image

### ISSUE THREAD

**Issue by ZichenMiao** [lukaskondmann/DENETHOR#3]
Hi Lukas,

Really appreciate your excellent work!

I would like to visualize the original tif images with RGB channels, just like the gif in the README. Could you please provide me with some lines of code to do it?

Thanks!

**Comment by lukaskondmann** [comment]
Hi, this specific .gif was done by a colleague of mine with QGIS conversion to .pngs. You could also automize this with the right normalization parameters:
```
import numpy as np
import matplotlib.pyplot as plt
import rasterio 
import glob

directory = '/localhome/kond_lu/crops/PlanetL3H/18E-242N/'
paths = glob.glob(directory + '2018-*-01.tif')
print(paths)

for path in paths: 
    ## Open GeoTiffs
    date = path.split('/')[-1].split('.')[0]
    image = rasterio.open(path).read()
    index = [2,1,0] # Red, Green, Blue Bands 
    rgb = image[index,:,:]/10000
    rgb /= rgb.max()
    
    plt.imshow(np.moveaxis(rgb[:3,:,:],0,-1))
    plt.imsave(directory + date +'.png',np.moveaxis(rgb[:3,:,:],0,-1))
    plt.show()
   ```

You can simply combine the .pngs to a gif with Python via something like this:

```
import os
import imageio

image_folder = '<path to pngs>'
gif_name = '<path to gif.gif>'

images = [os.path.join(image_folder,img) for img in os.listdir(image_folder) if img.endswith(".png")]
gif_f = []
for image in images:
    gif_f.append(imageio.imread(image))
imageio.mimsave(gif_name, gif_f)
```

**Comment by ZichenMiao** [comment]
Hi Lukas,

Thank you! I will have a try.

**Comment by ZichenMiao** [comment]
Hi Lukas,

I tried with the code below,

```
import os
import numpy as np
import matplotlib.pyplot as plt
import rasterio 
import cv2

data_path = "/data/dataset/DENETHOR/PlanetL3H/Train/PF-SR"
date = '2018-09-05'
data_file = os.path.join(data_path, date+'.tif')
print(data_file)

image = rasterio.open(data_file).read()
index = [2,1,0] # Blue, Green, Red 
rgb = image[index,:,:]/10000
rgb /= rgb.max()
rgb = np.transpose(rgb, (1, 2, 0)).astype(np.float32)

plt.figure(figsize=(10, 10))
plt.imshow(rgb)
plt.axis('off')
```

And the image looks too dim. 
![image](https://user-images.githubusercontent.com/63263970/154366719-41e0b03b-d5bb-415b-ae25-c397a9b8ec97.png)

Just want to know if it's because the publicly available images are from a different section of data?

**Comment by lukaskondmann** [comment]
no this is the same image but as I said we used QGIS for the .png conversion for the .gif in the repository. QGIS by default does min-max stretching as an enhancement for raster data which is where the contrast difference comes from. If you wanted to replicate this exactly you'd either need to use QGIS or switch this part:
```
rgb = image[index,:,:]/10000
rgb /= rgb.max()
```
with the kind of min-max stretching QGIS does. I don't know the exact parameters for this but more details are here:
https://gis.stackexchange.com/questions/328356/difference-between-contrast-enhancement-options-qgis-3-rasterlayer-symbology-mul/328357

**Comment by ZichenMiao** [comment]
Thanks so much. I got perfect visualization with QGIS.
![image](https://user-images.githubusercontent.com/63263970/155010951-95f545e9-637e-46c5-8e3e-ccc46d21092d.png)
