### ISSUE TITLE
How is Sentinel 2 read ?

### ISSUE THREAD

**Issue by ankitpatnala** [lukaskondmann/DENETHOR#4]
When I opened bands.npy, I saw the shape of numpy array to be (144,12,2400,2400)

I assume here 144 is time span, 12 is number of bands and 2400 X 2400 is spatial coordinate.

How is time span of 144 dimension given the Sentinel2 revisits 5-6 days which then I guess should be ~70 ?

Am i missing something ?

**Comment by lukaskondmann** [comment]
you are correct, 144 is indeed the time dimension. S2 maximum revisit time is 5 days with 2 satellites but many areas are actually visited more frequently, particularly close to the equator. See for example https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-2-msi/revisit-coverage
