### ISSUE TITLE
Question about label

### ISSUE THREAD

**Issue by zwxlyy1995** [lukaskondmann/DENETHOR#5]
Hello Lukas:

I'm interested in satellite image time series and I noticed you released two public available datasets:`Germany` and `South Africa`. I can download data from MLHub, but there is no ground truth information in both TEST sets. Specifically both `labels.geojson` files in TEST sets have only boundary information for each parcel with `crop name`  being `No Data` and `crop id` being `0`.  I find out the corresponding TEST ground truth is available in the download link of Ablation Study in this repo for `Germany` dataset. I wonder if you can release the TEST ground truth for `South Africa` dataset.

Your reply would be appreciated, thanks.

**Comment by lukaskondmann** [comment]
Hi, 

I just downloaded the test data for Germany from MLHub and it looks fine to me. See QGIS visualization of crop_id below:
![radiant_earth_brandenburg_test](https://user-images.githubusercontent.com/44567074/190992758-d6c32d90-4bb3-4f77-bd2b-449de11b855c.jpg)

It seems like the problem could be not MLHub related. Did you e.g. unzip the .tar.gz correctly? (First to tar, then unzip again).

**Comment by zwxlyy1995** [comment]
Hi, 

I redownloaded TEST collections for both datasets, and now the ground truth information is available. It seems that I downloaded data before the end date of the competition, when the ground truth is not revealed.

Thank you so much.
