### ISSUE TITLE
Need help to download data

### ISSUE THREAD

**Issue by ankitpatnala** [lukaskondmann/DENETHOR#7]
Hi Lukas,

I am planning to download the same Sentinel2 data but for 1C type. Do you have the download script for the same ? I want it to be properly aligned.

**Comment by lukaskondmann** [comment]
Unfortunately, I don't. But this should be a good starting point: https://docs.sentinel-hub.com/api/latest/data/sentinel-2-l1c/

**Comment by ankitpatnala** [comment]
I am facing problem in alignment.
